// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ServerContext))]
    partial class ServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Data.Market", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ButterPrice")
                        .HasColumnType("integer");

                    b.Property<int>("ChocolatePrice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EggsPrice")
                        .HasColumnType("integer");

                    b.Property<int>("FlourPrice")
                        .HasColumnType("integer");

                    b.Property<int>("MilkPrice")
                        .HasColumnType("integer");

                    b.Property<int>("SugarPrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("Server.Data.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Butter")
                        .HasColumnType("integer");

                    b.Property<int>("Chocolate")
                        .HasColumnType("integer");

                    b.Property<int>("Cookies")
                        .HasColumnType("integer");

                    b.Property<int>("Eggs")
                        .HasColumnType("integer");

                    b.Property<int>("Flour")
                        .HasColumnType("integer");

                    b.Property<int>("Milk")
                        .HasColumnType("integer");

                    b.Property<int>("Sugar")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
